<?php
    $pagesData = array(
        'math-ege-vid-main' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'folders' => array(
                array(
                    'name' => 'ЕГЭ 2024',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=ege2024',
                ),
            ),
            'videos' => false,
        ),
        'math-ege-vid-ege2024' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'folders' => array(
                array(
                    'name' => 'Разбор вариантов ЕГЭ 2024',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=variants',
                ),
                array(
                    'name' => '№1-12 первая часть',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num1_12',
                ),
                array(
                    'name' => '№13 Уравнения',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num13',
                ),
                array(
                    'name' => '№1, 17 Планиметрия',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num17',
                ),
                array(
                    'name' => '№18 Параметр',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num18',
                ),
                array(
                    'name' => '№19 Теория чисел',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num19',
                ),
            ),
            'videos' => false,
        ),
        'math-ege-vid-num1_12' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'folders' => array(
                array(
                    'name' => '№1 Планиметрия',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num1_planimetria',
                ),
                array(
                    'name' => '№2 Векторы',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num2_vectors',
                ),
                array(
                    'name' => '№3 Стереометрия',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num3_stereom',
                ),
                array(
                    'name' => '№4, 5 Теория вероятностей',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num4_5teorver',
                ),
                array(
                    'name' => '№6, 7 Решение уравнений',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num6_7equotions',
                ),
                array(
                    'name' => '№10 Сюжетные текстовые задачи',
                    'link' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=num10_texttasks',
                ),
            ),
            'videos'=>false,
        ),
        'math-ege-vid-variants' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'videos' => true,
            'folders' => array(),
        ),
        'math-ege-vid-num17' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'videos' => true,
            'folders' => array(),
        ),
        'math-ege-vid-num19' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'videos' => true,
            'folders' => array(),
        ),
        'math-ege-vid-num2_vectors' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'videos' => true,
            'folders' => array(),
        ),
        'math-ege-vid-num4_5teorver' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'videos' => true,
            'folders' => array(),
        ),
        'math-ege-vid-num6_7equotions' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'videos' => true,
            'folders' => false,
        ),
        'math-ege-vid-num6_num10_texttasks' => array(
            'ex' => 'егэ',
            'title' => 'математика',
            'subject' => 'математике',
            'lVideo' => 'catalog-page.php?page=math&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-math-2024-tasks/catalog-ege-math-tasks.php',
            'videos' => true,
            'folders' => array(),
        ),
        'fiz-ege-vid-main' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(
                array(
                    'name' => 'ЕГЭ 2024',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=ege2024',
                ),
            ),
            'videos' => false,
        ),
        'fiz-ege-vid-ege2024' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(
                array(
                    'name' => 'Векторы и проекции',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=vectors_proections',
                ),
                array(
                    'name' => 'Закон сохранения энергии и импульса',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=conservation_energy_momentum',
                ),
                array(
                    'name' => 'Полное ускорение. Равномероное движение по окружности',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=full_acceleration_uniform_movement_around_circle',
                ),
                array(
                    'name' => 'Полное ускорение. Равномероное движение по окружности',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=full_acceleration_uniform_movement_around_circle',
                ),
                array(
                    'name' => 'Кинематика',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=kinematics',
                ),
                array(
                    'name' => 'Разбор вариантов ЕГЭ',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=variants',
                ),
                array(
                    'name' => 'Свободное падение. Баллистика',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=free_fall_ballistics',
                ),
                array(
                    'name' => 'Основы МКТ',
                    'link' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=free_fall_basics_mkt',
                ),
            ),
            'videos' => false,
        ),
        'fiz-ege-vid-vectors_proections' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'fiz-ege-vid-conservation_energy_momentum' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'fiz-ege-vid-full_acceleration_uniform_movement_around_circle' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'fiz-ege-vid-kinematics' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'fiz-ege-vid-variants' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'fiz-ege-vid-free_fall_ballistics' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'fiz-ege-vid-free_fall_basics_mkt' => array(
            'ex' => 'егэ',
            'title' => 'физика',
            'subject' => 'физике',
            'lVideo' => 'catalog-page.php?page=fiz&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-fiz-2024-tasks/catalog-ege-fiz-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'him-ege-vid-main' => array(
            'ex' => 'егэ',
            'title' => 'химия',
            'subject' => 'химии',
            'lVideo' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-him-2024-tasks/catalog-ege-him-tasks.php',
            'folders' => array(
                array(
                    'name' => 'ЕГЭ 2024',
                    'link' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=ege2024',
                ),
            ),
            'videos' => false,
        ),
        'him-ege-vid-ege2024' => array(
            'ex' => 'егэ',
            'title' => 'химия',
            'subject' => 'химии',
            'lVideo' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-him-2024-tasks/catalog-ege-him-tasks.php',
            'folders' => array(
                array(
                    'name' => 'Периодический закон',
                    'link' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=periodic_law',
                ),
                array(
                    'name' => 'Практика. Задания 1-3',
                    'link' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=practika1_3',
                ),
                array(
                    'name' => 'Степень окисления. Валентность',
                    'link' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=oxidation_valence',
                ),
                array(
                    'name' => 'Строение атома. Электронные конфигурации',
                    'link' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=atom_electronic_configurations',
                ),
            ),
            'videos' => false,
        ),
        'him-ege-vid-periodic_law' => array(
            'ex' => 'егэ',
            'title' => 'химия',
            'subject' => 'химии',
            'lVideo' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-him-2024-tasks/catalog-ege-him-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'him-ege-vid-practika1_3' => array(
            'ex' => 'егэ',
            'title' => 'химия',
            'subject' => 'химии',
            'lVideo' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-him-2024-tasks/catalog-ege-him-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'him-ege-vid-oxidation_valence' => array(
            'ex' => 'егэ',
            'title' => 'химия',
            'subject' => 'химии',
            'lVideo' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-him-2024-tasks/catalog-ege-him-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'him-ege-vid-atom_electronic_configurations' => array(
            'ex' => 'егэ',
            'title' => 'химия',
            'subject' => 'химии',
            'lVideo' => 'catalog-page.php?page=him&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-him-2024-tasks/catalog-ege-him-tasks.php',
            'folders' => array(),
            'videos' => true,
        ),
        'inf-ege-vid-main' => array(
            'ex' => 'егэ',
            'title' => 'информатика',
            'subject' => 'информатике',
            'lVideo' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-inf-2024-tasks/catalog-ege-him-tasks.php',
            'folders' => array(
                array(
                    'name' => 'ЕГЭ 2024',
                    'link' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=ege2024',
                ),
            ),
            'videos' => false,
        ),
        'inf-ege-vid-ege2024' => array(
            'ex' => 'егэ',
            'title' => 'информатика',
            'subject' => 'информатике',
            'lVideo' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-inf-2024-tasks/catalog-ege-inf-tasks.php',
            'folders' => array(
                array(
                    'name' => 'Логические операции и графы (задание 1, 2, 4)',
                    'link' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=logic_operations_graf_124',
                ),
                array(
                    'name' => 'Объем информации (задание 7, 11)',
                    'link' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=information_amount',
                ),
                array(
                    'name' => 'Количество способов, ip-адреса (задание 8, 13)',
                    'link' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=ip_8_13',
                ),
            ),
            'videos' => false,
        ),
        'inf-ege-vid-logic_operations_graf_124' => array(
            'ex' => 'егэ',
            'title' => 'информатика',
            'subject' => 'информатике',
            'lVideo' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-inf-2024-tasks/catalog-ege-inf-tasks.php',
            'folders' => array(),
            'videos' =>true,
        ),
        'inf-ege-vid-information_amount' => array(
            'ex' => 'егэ',
            'title' => 'информатика',
            'subject' => 'информатике',
            'lVideo' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-inf-2024-tasks/catalog-ege-inf-tasks.php',
            'folders' => array(),
            'videos' =>true,
        ),
        'inf-ege-vid-ip_8_13' => array(
            'ex' => 'егэ',
            'title' => 'информатика',
            'subject' => 'информатике',
            'lVideo' => 'catalog-page.php?page=inf&type=ege&sec=vid&lvl=main',
            'lTasks' => 'catalog-ege-inf-2024-tasks/catalog-ege-inf-tasks.php',
            'folders' => array(),
            'videos' =>true,
        ),

    )
?>